name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      flake-lock-changed: ${{ steps.commit-flake-lock.outputs.changes_detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update lock
        id: nix-update
        run: |
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          nix flake update &>> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit changes
        id: commit-flake-lock
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: |
            chore: auto update `flake.lock`

            ${{ steps.nix-update.outputs.changes }}

  generate-files:
    needs: update-lock
    if: needs.update-lock.outputs.flake-lock-changed == 'true'
    uses: ./.github/workflows/generate.yml
    permissions:
      contents: write
